Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,7 +2,9 @@ name: Deploy to ECS
 
 on:
   push:
-    branches: [ master ]  # Adjust the branch to trigger on
+    branches: [ "master" ]
+  pull_request:
+    branches: [ "master" ]
 
 jobs:
   deploy:
@@ -14,16 +16,26 @@ jobs:
         with:
           fetch-depth: 1
 
-      - name: Set up SSH agent
-        run: |
-          echo "## Setting up SSH agent"
-          eval "$(ssh-agent -s)"
-          echo "${{ secrets.PASSPHRASE }}" | ssh-add ${{ secrets.KEY }}
-          if [ $? -ne 0 ]; then
-            echo "## Error adding SSH key to agent"
-            exit 1
-          fi
-          echo "## SSH Connection estabilished"
+      - uses: actions/checkout@v3
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: 'npm'
+      - run: npm ci
+      - run: npm run build --if-present
+      - run: npm test
+
+      # - name: Set up SSH agent
+      #   run: |
+      #     echo "## Setting up SSH agent"
+      #     eval "$(ssh-agent -s)"
+      #     echo "${{ secrets.PASSPHRASE }}" | ssh-add ${{ secrets.KEY }}
+      #     if [ $? -ne 0 ]; then
+      #       echo "## Error adding SSH key to agent"
+      #       exit 1
+      #     fi
+      #     echo "## SSH Connection estabilished"
 
       #   env:
       #     SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
