Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,18 +24,18 @@ jobs:
           cache: 'npm'
       - run: npm ci
       - run: npm run build --if-present
-      - run: npm test
+      # - run: npm test
 
-      # - name: Set up SSH agent
-      #   run: |
-      #     echo "## Setting up SSH agent"
-      #     eval "$(ssh-agent -s)"
-      #     echo "${{ secrets.PASSPHRASE }}" | ssh-add ${{ secrets.KEY }}
-      #     if [ $? -ne 0 ]; then
-      #       echo "## Error adding SSH key to agent"
-      #       exit 1
-      #     fi
-      #     echo "## SSH Connection estabilished"
+      - name: Set up SSH agent
+        run: |
+          echo "## Setting up SSH agent"
+          eval "$(ssh-agent -s)"
+          echo "${{ secrets.PASSPHRASE }}" | ssh-add ${{ secrets.KEY }}
+          if [ $? -ne 0 ]; then
+            echo "## Error adding SSH key to agent"
+            exit 1
+          fi
+          echo "## SSH Connection estabilished"
 
       #   env:
       #     SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
